### ISSUE TITLE
Wifi network enumeration (normal)

### ISSUE THREAD

**Issue by Kkevsterrr** [ecthros/pina-colada#113]
https://wifi.readthedocs.io/en/latest/scanning.html

**Comment by ecthros** [comment]
Is this better than what we have right now?

**Comment by Kkevsterrr** [comment]
It's not necessarily better, just different - what we have now is (very very basic and largely untested) code that reads out beacons off raw sockets, looking for wifi advertisements, the above just calls down into the kernel to find the networks the pi is already aware of

**Comment by Kkevsterrr** [comment]
Which is faster & more reliable

**Comment by ecthros** [comment]
After about an hour of trying to figure out the python-wifi command, I found this comment:

"This returns a list of :class:`Cell` objects. Under the hood, this calls iwlist scan and parses the unfriendly output."

Which is what I did originally, although I think it got changed?

**Comment by ecthros** [comment]
https://github.com/ecthros/pina-colada/blob/bc03a4dccc5a7f273e38e6b70cba5f8c48bea89f/scans.py

This contains the function wifi_scan, which actually probably works faster than what you're asking for.
