### ISSUE TITLE
Trademark Infringement

### ISSUE THREAD

**Issue by hak5darren** [ecthros/pina-colada#142]
Hi guys - cool project. I like the command line functionality. As the founder of Hak5 and the WiFi Pineapple project I'm not keen on you using the term "WiFi Pineapple" without my express permission. I know you didn't mean anything hostile by it - but this is one of those things where if I don't protect my trademark, I lose it. Thanks for understanding and best of luck with the project.

Legal stuff advised by my attorney:

It has come to my attention that you are using the WIFI PINEAPPLE trademark. The trademark is deceptively similar to our trademark Registration Number 4651494, WIFI PINEAPPLE word mark. This constitutes a reproduction or counterfeit imitation thereof. Your use of the trademark will constitute an infringement of our registered and common law rights. I demand that you cease and desist from this activity as soon as possible and in the event, within 5 days from your receipt of this letter. If action is not taken by you to cease and desist within the given time frame, I will have no choice but to take appropriate legal action against you.

Sincerely,
Darren Kitchen
Manager, Hak5 LLC

**Comment by Kkevsterrr** [comment]
Hey @hak5darren - 

Thanks so much for your note. We sincerely apologize - we had no idea "Wifi Pineapple" was trademarked, and had no intention of interfering. We will remove the term from our repository and code base immediately. Thanks for reaching out, and please don't hesitate to reach out with any other questions or concerns. 

Best,
Piña Colada Team

**Comment by hak5darren** [comment]
<3

**Comment by ecthros** [comment]
<3 let us know if there's anything else!
