### ISSUE TITLE
Vulnerability scanning

### ISSUE THREAD

**Issue by ecthros** [ecthros/pina-colada#26]
Things like scanning for MS08 vulnerabilities, FTP anonymous, etc

**Comment by Kkevsterrr** [comment]
Idk if we want to try to write this ourself, or just call out to burp or something

**Comment by Kkevsterrr** [comment]
@ecthros thoughts on keeping this open? Think I'd rather just have the setup script install metasploit or something and just let the user handle it

**Comment by ecthros** [comment]
yeah this one was waaay in the future and I think it actually pretty good now that we have some legit scanning going. If we want to implement stuff further down the road this would be the way to go but as of now it's not the direction we're going.
