### ISSUE TITLE
Automatically set up a pi

### ISSUE THREAD

**Issue by ecthros** [ecthros/pina-colada#41]
Dependencies:

Postgres database (create script to do this automatically)
impacket from https://github.com/CoreSecurity/impacket

**Comment by ecthros** [comment]
sudo apt install python-netaddr

**Comment by ecthros** [comment]
% sudo apt-get install build-essential python-dev libnetfilter-queue-dev
% git clone https://github.com/fqrouter/python-netfilterqueue.git
% cd python-netfilterqueue
% python setup.py install

**Comment by ecthros** [comment]
apt install python-nmap

**Comment by Kkevsterrr** [comment]
pip install:
netifaces
scapy
netaddr
pexpect
colorama

**Comment by ecthros** [comment]
https://pypi.python.org/packages/bc/ab/c49f97516f78c2b0cacb4f45873abc4ca9872942a9c4c19ded8052c8edda/python-wifi-0.6.1.tar.bz2

**Comment by sandrasandeep** [comment]
Done - ish.
