### ISSUE TITLE
integrate scans.py

### ISSUE THREAD

**Issue by Kkevsterrr** [ecthros/pina-colada#58]

**Comment by ecthros** [comment]
We want scans to be happening in the background basically constantly, as well as sniffing (which I put in the packets directory

**Comment by Kkevsterrr** [comment]
I don't know if scanning by default is the best practice - it'd be pretty loud to begin aggressively scanning as soon as you're connected. I think it'd be better to set that as an option. Passive sniffing is fine though

**Comment by ecthros** [comment]
Cool. I'm gonna close #19 because they're pretty similar now

**Comment by ecthros** [comment]
Half done. An initialization scan is done on port 22 to check for ssh, but no other ports - the next step is creating a capability to scan.
