### ISSUE TITLE
create testing framework (with docker)

### ISSUE THREAD

**Issue by Kkevsterrr** [ecthros/pina-colada#61]

**Comment by ecthros** [comment]
There's already a Docker box on the network, shouldn't be too tough to add some testing framework. What are you looking for?

**Comment by Kkevsterrr** [comment]
I want us to be able to use travis, which means when it runs a test, we need a script that can create a docker machine or two for our thing to scan

**Comment by ecthros** [comment]
how are we looking for this? I don't have much experience with docker :(

**Comment by Kkevsterrr** [comment]
I've actually just started playing around with this, so I"ll keep you posted
