### ISSUE TITLE
scanning shouldn't be default behavior

### ISSUE THREAD

**Issue by Kkevsterrr** [ecthros/pina-colada#73]
too loud - should be something triggered (either by a capability or command directly)

**Comment by ecthros** [comment]
I can change this easy - was actually thinking of doing it. 

What about the arp ping that it does at the start every time? It does this to profile the network and fill in the postgres table, so maybe it's too loud? It is suspicious and generally doesn't happen

**Comment by Kkevsterrr** [comment]
That was the scanning I was referring to - I don't think it should be default behavior. Idk if we just want to make it another capability?

**Comment by ecthros** [comment]
ohhh because it also scans port 22 on all the computers it finds up...
