### ISSUE TITLE
Controlling capabilities

### ISSUE THREAD

**Issue by ecthros** [ecthros/pina-colada#83]
I want to be able to control the capability after I've closed out of it, so that I can be working on other capabilities or attack other devices on the network.

For example, the DNS capability requires that we own their traffic. To own their traffic, we have to enter promiscuous mode or arp spoof them. Then we have to cancel out of that module, go to dns, start that up - and then we can't restore the target from being arp spoofed.

**Comment by Kkevsterrr** [comment]
Hmmm I'll think about how we can do this

**Comment by ecthros** [comment]
Can we just keep an array of all modified computers?

**Comment by Kkevsterrr** [comment]
So capabilities are now persistent (when you exit out of it and reenter it, it's the same object, so everything you did sticks around). Is this what you were looking for?
