### ISSUE TITLE
Drawer List

### ISSUE THREAD

**Issue by jottenwa** [ecthros/pina-colada#94]
Dynamically create drawer labels for different commands found on the pi.

**Comment by Kkevsterrr** [comment]
Can you also dynamically generate them in categories? 
Like for example, there's a scanning category, which has a bunch of capabilities beneath it. Instead of just a huge list of capabilities, can it be organized?

**Comment by jottenwa** [comment]
Give me to the end of the night. This is a secondary priority behind being able to connect and send/receive messages.

**Comment by jottenwa** [comment]
But yes. This will be done.
